"""initial schema

Revision ID: 5480cd62d6a6
Revises: 
Create Date: 2026-09-10 20:25:36.753008
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector
import pgvector.sqlalchemy

from app.config import settings

revision: str = '5480cd62d6a6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any VECTOR column / HNSW index below
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('applies_to', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['doc_chunks.id'], name='fk_academic_calendar_source_chunk_id', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('university_email', sa.String(), nullable=False),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_admins_university_email'), 'admins', ['university_email'], unique=False)
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('hod_faculty_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hod_faculty_id'], ['faculty.id'], name='fk_departments_hod_faculty_id', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('audience_roles', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('source_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subjects',
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('component', sa.String(), nullable=True),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('tutorial_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.PrimaryKeyConstraint('subject_code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('subject_ref', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('announcements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('scope_ref', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('audience_roles', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('tool_name', sa.String(), nullable=False),
    sa.Column('args', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('rows_returned', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('classrooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('building', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('room_type', sa.String(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_table('curriculum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('is_elective', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('doc_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('parent_chunk_id', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tsv', postgresql.TSVECTOR(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=settings.embedding_dim), nullable=True),
    sa.Column('embedding_model', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
    sa.ForeignKeyConstraint(['parent_chunk_id'], ['doc_chunks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doc_chunks_document_id'), 'doc_chunks', ['document_id'], unique=False)
    op.create_index('ix_doc_chunks_embedding_hnsw', 'doc_chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.create_index('ix_doc_chunks_tsv', 'doc_chunks', ['tsv'], unique=False, postgresql_using='gin')
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('university_email', sa.String(), nullable=False),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('designation', sa.String(), nullable=True),
    sa.Column('is_hod', sa.Boolean(), nullable=False),
    sa.Column('date_of_joining', sa.Date(), nullable=True),
    sa.Column('qualification', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.Column('office_room', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_faculty_dept_id'), 'faculty', ['dept_id'], unique=False)
    op.create_index(op.f('ix_faculty_university_email'), 'faculty', ['university_email'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('university_email', sa.String(), nullable=False),
    sa.Column('personal_email', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('address_city', sa.String(), nullable=True),
    sa.Column('address_state', sa.String(), nullable=True),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('lab_group', sa.String(), nullable=True),
    sa.Column('tenth_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('twelfth_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('is_hosteller', sa.Boolean(), nullable=True),
    sa.Column('guardian_name', sa.String(), nullable=True),
    sa.Column('guardian_phone', sa.String(), nullable=True),
    sa.Column('admission_date', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_students_dept_id'), 'students', ['dept_id'], unique=False)
    op.create_index(op.f('ix_students_roll_no'), 'students', ['roll_no'], unique=True)
    op.create_index(op.f('ix_students_university_email'), 'students', ['university_email'], unique=False)
    op.create_table('course_offerings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('batch', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('lab_group', sa.String(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_offerings_faculty_id'), 'course_offerings', ['faculty_id'], unique=False)
    op.create_index(op.f('ix_course_offerings_subject_code'), 'course_offerings', ['subject_code'], unique=False)
    op.create_index(op.f('ix_course_offerings_term'), 'course_offerings', ['term'], unique=False)
    op.create_table('document_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('requested_on', sa.Date(), nullable=True),
    sa.Column('ready_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_requests_student_id'), 'document_requests', ['student_id'], unique=False)
    op.create_table('exam_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('exam_type', sa.String(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('dept_code', sa.String(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('amount_due', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('paid_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fees_student_id'), 'fees', ['student_id'], unique=False)
    op.create_table('leave_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('from_date', sa.Date(), nullable=False),
    sa.Column('to_date', sa.Date(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_on', sa.Date(), nullable=True),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leave_requests_student_id'), 'leave_requests', ['student_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_conversation_id'), 'messages', ['conversation_id'], unique=False)
    op.create_table('results_semester',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('credits_registered', sa.Integer(), nullable=True),
    sa.Column('credits_earned', sa.Integer(), nullable=True),
    sa.Column('sgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('cgpa', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('result_status', sa.String(), nullable=True),
    sa.Column('backlogs', sa.Integer(), nullable=True),
    sa.Column('declared_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_semester_student_id'), 'results_semester', ['student_id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('roll_no', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('applied_on', sa.Date(), nullable=True),
    sa.Column('decided_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_student_id'), 'scholarships', ['student_id'], unique=False)
    op.create_table('teaching_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('subject_name', sa.String(), nullable=True),
    sa.Column('batch', sa.Integer(), nullable=True),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('division', sa.String(), nullable=True),
    sa.Column('lab_group', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_assignments_faculty_id'), 'teaching_assignments', ['faculty_id'], unique=False)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('term', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('max_marks', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('weightage_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assessments_offering_id'), 'assessments', ['offering_id'], unique=False)
    op.create_table('attendance_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('slot_no', sa.Integer(), nullable=True),
    sa.Column('marked_by', sa.Integer(), nullable=True),
    sa.Column('marked_at', sa.DateTime(), nullable=True),
    sa.Column('topic_no', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['marked_by'], ['faculty.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_sessions_offering_id'), 'attendance_sessions', ['offering_id'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('subject_code', sa.String(), nullable=False),
    sa.Column('term', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('enrolled_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_enrollments_offering_student', 'enrollments', ['offering_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_enrollments_student_id'), 'enrollments', ['student_id'], unique=False)
    op.create_table('timetable_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offering_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('classroom_id', sa.Integer(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['classroom_id'], ['classrooms.id'], ),
    sa.ForeignKeyConstraint(['offering_id'], ['course_offerings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timetable_slots_offering_id'), 'timetable_slots', ['offering_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['attendance_sessions.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attendance_records_student_session', 'attendance_records', ['student_id', 'session_id'], unique=False)
    op.create_table('marks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('is_absent', sa.Boolean(), nullable=False),
    sa.Column('graded_on', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marks_assessment_id'), 'marks', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_marks_student_id'), 'marks', ['student_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assessment_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assessment_id'], ['assessments.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_assessment_id'), 'submissions', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_submissions_student_id'), 'submissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_student_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_assessment_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_marks_student_id'), table_name='marks')
    op.drop_index(op.f('ix_marks_assessment_id'), table_name='marks')
    op.drop_table('marks')
    op.drop_index('ix_attendance_records_student_session', table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_timetable_slots_offering_id'), table_name='timetable_slots')
    op.drop_table('timetable_slots')
    op.drop_index(op.f('ix_enrollments_student_id'), table_name='enrollments')
    op.drop_index('ix_enrollments_offering_student', table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_attendance_sessions_offering_id'), table_name='attendance_sessions')
    op.drop_table('attendance_sessions')
    op.drop_index(op.f('ix_assessments_offering_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_teaching_assignments_faculty_id'), table_name='teaching_assignments')
    op.drop_table('teaching_assignments')
    op.drop_index(op.f('ix_scholarships_student_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_results_semester_student_id'), table_name='results_semester')
    op.drop_table('results_semester')
    op.drop_index(op.f('ix_messages_conversation_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_leave_requests_student_id'), table_name='leave_requests')
    op.drop_table('leave_requests')
    op.drop_index(op.f('ix_fees_student_id'), table_name='fees')
    op.drop_table('fees')
    op.drop_table('exam_schedule')
    op.drop_index(op.f('ix_document_requests_student_id'), table_name='document_requests')
    op.drop_table('document_requests')
    op.drop_index(op.f('ix_course_offerings_term'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_subject_code'), table_name='course_offerings')
    op.drop_index(op.f('ix_course_offerings_faculty_id'), table_name='course_offerings')
    op.drop_table('course_offerings')
    op.drop_index(op.f('ix_students_university_email'), table_name='students')
    op.drop_index(op.f('ix_students_roll_no'), table_name='students')
    op.drop_index(op.f('ix_students_dept_id'), table_name='students')
    op.drop_table('students')
    op.drop_index(op.f('ix_faculty_university_email'), table_name='faculty')
    op.drop_index(op.f('ix_faculty_dept_id'), table_name='faculty')
    op.drop_table('faculty')
    op.drop_index('ix_doc_chunks_tsv', table_name='doc_chunks', postgresql_using='gin')
    op.drop_index('ix_doc_chunks_embedding_hnsw', table_name='doc_chunks', postgresql_using='hnsw', postgresql_with={'m': 16, 'ef_construction': 64}, postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_doc_chunks_document_id'), table_name='doc_chunks')
    op.drop_table('doc_chunks')
    op.drop_table('curriculum')
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_table('classrooms')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('announcements')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('subjects')
    op.drop_table('documents')
    op.drop_table('departments')
    op.drop_index(op.f('ix_admins_university_email'), table_name='admins')
    op.drop_table('admins')
    op.drop_table('academic_calendar')
    # ### end Alembic commands ###
    op.execute("DROP EXTENSION IF EXISTS vector")
