"""syllabus tables

Revision ID: cc3862737634
Revises: 5480cd62d6a6
Create Date: 2026-09-11 21:22:23.199926
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'cc3862737634'
down_revision: str | None = '5480cd62d6a6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # autogenerated; the two pre-existing use_alter FKs it re-detected were removed by hand
    op.create_table('syllabus_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('dept_code', sa.String(), nullable=True),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('subject_code', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_key', sa.String(), nullable=False),
    sa.Column('lecture_hours', sa.Integer(), nullable=True),
    sa.Column('tutorial_hours', sa.Integer(), nullable=True),
    sa.Column('practical_hours', sa.Integer(), nullable=True),
    sa.Column('credits', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('objectives', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['doc_chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subject_code'], ['subjects.subject_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_courses_code'), 'syllabus_courses', ['code'], unique=False)
    op.create_index(op.f('ix_syllabus_courses_document_id'), 'syllabus_courses', ['document_id'], unique=False)
    op.create_index(op.f('ix_syllabus_courses_subject_code'), 'syllabus_courses', ['subject_code'], unique=False)
    op.create_index('ix_syllabus_courses_title_key', 'syllabus_courses', ['title_key'], unique=False)
    op.create_table('course_outcomes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['syllabus_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['doc_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_outcomes_course_id'), 'course_outcomes', ['course_id'], unique=False)
    op.create_table('syllabus_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('hours', sa.Integer(), nullable=True),
    sa.Column('topics', sa.Text(), nullable=True),
    sa.Column('page', sa.Integer(), nullable=True),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['syllabus_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['doc_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_syllabus_units_course_id'), 'syllabus_units', ['course_id'], unique=False)
    op.create_table('textbooks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('citation', sa.Text(), nullable=False),
    sa.Column('source_chunk_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['syllabus_courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_chunk_id'], ['doc_chunks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_textbooks_course_id'), 'textbooks', ['course_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_textbooks_course_id'), table_name='textbooks')
    op.drop_table('textbooks')
    op.drop_index(op.f('ix_syllabus_units_course_id'), table_name='syllabus_units')
    op.drop_table('syllabus_units')
    op.drop_index(op.f('ix_course_outcomes_course_id'), table_name='course_outcomes')
    op.drop_table('course_outcomes')
    op.drop_index('ix_syllabus_courses_title_key', table_name='syllabus_courses')
    op.drop_index(op.f('ix_syllabus_courses_subject_code'), table_name='syllabus_courses')
    op.drop_index(op.f('ix_syllabus_courses_document_id'), table_name='syllabus_courses')
    op.drop_index(op.f('ix_syllabus_courses_code'), table_name='syllabus_courses')
    op.drop_table('syllabus_courses')
    # ### end Alembic commands ###
